name: 'linesight'
version: '1.0.0'
config-version: 2

profile: 'linesight'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"

models:
  linesight:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
